language: python
python:
#  - "3.5-dev"
  - "nightly"

sudo: false

#install:
  #- pip install -r whichever library needs to be installed

before_script:
  - chmod +x ./tests/test_basics.py
  - python ./tests/test_basics.py install

script:
  - ./tests/test_basics.py
#  - ./tests/test_graphs.py
